version: "3.8"
services:
  frontend:
    build: ./frontend
    image: ${DOCKER_HUB_CREDS_USR}/bc-app-frontend:latest
    container_name: bc-app-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    build: ./backend
    image: ${DOCKER_HUB_CREDS_USR}/bc-app-backend:latest
    container_name: bc-app-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000

      